services:
  web:
    build:
      context: .
      dockerfile: dotnet/HitsInternship.Api/Dockerfile
    environment:
      DATABASE_CONNECTION_STRING: Server=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      Kafka__BootstrapServers: kafka:29092
      ASPNETCORE_ENVIRONMENT: Testing
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"
    networks:
      - postgres_postgres-network
      - docker_kafka-network 

networks:
  docker_kafka-network:
  postgres_postgres-network:
    driver: bridge

volumes:
  minio_data:
  pgdata:
